[phases.setup]
nixPkgs = ["python311", "gcc", "libGL", "libGLU"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn api:app --host 0.0.0.0 --port $PORT"

