services:
  - type: web
    name: rizz
    env: python
    buildCommand: chmod +x build.sh && ./build.sh || pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: cd web/web && gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --threads 2 server:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000
    healthCheckPath: /

